#!/bin/bash
rm GADGET/data/datasets/albertaFloods2013/InformationWanted/*.txt
rm GADGET/data/datasets/albertaFloods2013/Weather/*.txt
rm GADGET/data/datasets/albertaFloods2013/GoodsServices/*.txt
rm GADGET/data/datasets/albertaFloods2013/Discussion/*.txt
rm GADGET/data/datasets/albertaFloods2013/Advice/*.txt
rm GADGET/data/datasets/albertaFloods2013/CleanUp/*.txt
rm GADGET/data/datasets/albertaFloods2013/Official/*.txt
rm GADGET/data/datasets/albertaFloods2013/Factoid/*.txt
rm GADGET/data/datasets/albertaFloods2013/Irrelevant/*.txt
rm GADGET/data/datasets/albertaFloods2013/PastNews/*.txt
rm GADGET/data/datasets/albertaFloods2013/Hashtags/*.txt
rm GADGET/data/datasets/albertaFloods2013/SearchAndRescue/*.txt
rm GADGET/data/datasets/albertaFloods2013/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/albertaFloods2013/MovePeople/*.txt
rm GADGET/data/datasets/albertaFloods2013/Donations/*.txt
rm GADGET/data/datasets/albertaFloods2013/EmergingThreats/*.txt
rm GADGET/data/datasets/albertaFloods2013/ServiceAvailable/*.txt
rm GADGET/data/datasets/albertaFloods2013/ContinuingNews/*.txt
rm GADGET/data/datasets/albertaFloods2013/Volunteer/*.txt
rm GADGET/data/datasets/albertaFloods2013/Unknown/*.txt
rm GADGET/data/datasets/albertaFloods2013/Sentiment/*.txt
rm GADGET/data/datasets/albertaFloods2013/SignificantEventChange/*.txt
rm GADGET/data/datasets/albertaFloods2013/FirstPartyObservation/*.txt
rm GADGET/data/datasets/albertaFloods2013/MultimediaShare/*.txt
rm GADGET/data/datasets/albertaFloods2013/KnownAlready/*.txt
rm GADGET/data/datasets/queenslandFloods2013/InformationWanted/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Weather/*.txt
rm GADGET/data/datasets/queenslandFloods2013/GoodsServices/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Discussion/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Advice/*.txt
rm GADGET/data/datasets/queenslandFloods2013/CleanUp/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Official/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Factoid/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Irrelevant/*.txt
rm GADGET/data/datasets/queenslandFloods2013/PastNews/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Hashtags/*.txt
rm GADGET/data/datasets/queenslandFloods2013/SearchAndRescue/*.txt
rm GADGET/data/datasets/queenslandFloods2013/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/queenslandFloods2013/MovePeople/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Donations/*.txt
rm GADGET/data/datasets/queenslandFloods2013/EmergingThreats/*.txt
rm GADGET/data/datasets/queenslandFloods2013/ServiceAvailable/*.txt
rm GADGET/data/datasets/queenslandFloods2013/ContinuingNews/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Volunteer/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Unknown/*.txt
rm GADGET/data/datasets/queenslandFloods2013/Sentiment/*.txt
rm GADGET/data/datasets/queenslandFloods2013/SignificantEventChange/*.txt
rm GADGET/data/datasets/queenslandFloods2013/FirstPartyObservation/*.txt
rm GADGET/data/datasets/queenslandFloods2013/MultimediaShare/*.txt
rm GADGET/data/datasets/queenslandFloods2013/KnownAlready/*.txt
rm GADGET/data/datasets/Bombing_features/InformationWanted/*.txt
rm GADGET/data/datasets/Bombing_features/GoodsServices/*.txt
rm GADGET/data/datasets/Bombing_features/Discussion/*.txt
rm GADGET/data/datasets/Bombing_features/Advice/*.txt
rm GADGET/data/datasets/Bombing_features/Official/*.txt
rm GADGET/data/datasets/Bombing_features/Factoid/*.txt
rm GADGET/data/datasets/Bombing_features/Irrelevant/*.txt
rm GADGET/data/datasets/Bombing_features/PastNews/*.txt
rm GADGET/data/datasets/Bombing_features/Hashtags/*.txt
rm GADGET/data/datasets/Bombing_features/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/Bombing_features/Donations/*.txt
rm GADGET/data/datasets/Bombing_features/EmergingThreats/*.txt
rm GADGET/data/datasets/Bombing_features/ServiceAvailable/*.txt
rm GADGET/data/datasets/Bombing_features/ContinuingNews/*.txt
rm GADGET/data/datasets/Bombing_features/Volunteer/*.txt
rm GADGET/data/datasets/Bombing_features/Sentiment/*.txt
rm GADGET/data/datasets/Bombing_features/SignificantEventChange/*.txt
rm GADGET/data/datasets/Bombing_features/FirstPartyObservation/*.txt
rm GADGET/data/datasets/Bombing_features/MultimediaShare/*.txt
rm GADGET/data/datasets/Bombing_features/KnownAlready/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/InformationWanted/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Weather/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/GoodsServices/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Discussion/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Advice/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/CleanUp/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Official/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Factoid/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Irrelevant/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/PastNews/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Hashtags/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/SearchAndRescue/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/MovePeople/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Donations/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/EmergingThreats/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/ServiceAvailable/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/ContinuingNews/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Volunteer/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Unknown/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/Sentiment/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/SignificantEventChange/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/FirstPartyObservation/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/MultimediaShare/*.txt
rm GADGET/data/datasets/guatemalaEarthquake2012/KnownAlready/*.txt
rm GADGET/data/datasets/fire_features/InformationWanted/*.txt
rm GADGET/data/datasets/fire_features/Weather/*.txt
rm GADGET/data/datasets/fire_features/Discussion/*.txt
rm GADGET/data/datasets/fire_features/Advice/*.txt
rm GADGET/data/datasets/fire_features/Official/*.txt
rm GADGET/data/datasets/fire_features/Factoid/*.txt
rm GADGET/data/datasets/fire_features/Irrelevant/*.txt
rm GADGET/data/datasets/fire_features/PastNews/*.txt
rm GADGET/data/datasets/fire_features/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/fire_features/MovePeople/*.txt
rm GADGET/data/datasets/fire_features/Donations/*.txt
rm GADGET/data/datasets/fire_features/EmergingThreats/*.txt
rm GADGET/data/datasets/fire_features/ServiceAvailable/*.txt
rm GADGET/data/datasets/fire_features/ContinuingNews/*.txt
rm GADGET/data/datasets/fire_features/Volunteer/*.txt
rm GADGET/data/datasets/fire_features/Sentiment/*.txt
rm GADGET/data/datasets/fire_features/SignificantEventChange/*.txt
rm GADGET/data/datasets/fire_features/FirstPartyObservation/*.txt
rm GADGET/data/datasets/fire_features/MultimediaShare/*.txt
rm GADGET/data/datasets/fire_features/KnownAlready/*.txt
rm GADGET/data/datasets/Attacks_features/Discussion/*.txt
rm GADGET/data/datasets/Attacks_features/Advice/*.txt
rm GADGET/data/datasets/Attacks_features/Official/*.txt
rm GADGET/data/datasets/Attacks_features/Factoid/*.txt
rm GADGET/data/datasets/Attacks_features/Irrelevant/*.txt
rm GADGET/data/datasets/Attacks_features/Hashtags/*.txt
rm GADGET/data/datasets/Attacks_features/SearchAndRescue/*.txt
rm GADGET/data/datasets/Attacks_features/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/Attacks_features/EmergingThreats/*.txt
rm GADGET/data/datasets/Attacks_features/ServiceAvailable/*.txt
rm GADGET/data/datasets/Attacks_features/ContinuingNews/*.txt
rm GADGET/data/datasets/Attacks_features/Unknown/*.txt
rm GADGET/data/datasets/Attacks_features/Sentiment/*.txt
rm GADGET/data/datasets/Attacks_features/SignificantEventChange/*.txt
rm GADGET/data/datasets/Attacks_features/FirstPartyObservation/*.txt
rm GADGET/data/datasets/Attacks_features/MultimediaShare/*.txt
rm GADGET/data/datasets/Attacks_features/KnownAlready/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/InformationWanted/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Weather/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/GoodsServices/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Discussion/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Advice/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/CleanUp/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Official/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Factoid/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Irrelevant/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/PastNews/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Hashtags/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/SearchAndRescue/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/MovePeople/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Donations/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/EmergingThreats/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/ServiceAvailable/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/ContinuingNews/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Volunteer/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Unknown/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/Sentiment/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/SignificantEventChange/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/FirstPartyObservation/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/MultimediaShare/*.txt
rm GADGET/data/datasets/nepalEarthquake2015/KnownAlready/*.txt
rm GADGET/data/datasets/manilaFloods2013/InformationWanted/*.txt
rm GADGET/data/datasets/manilaFloods2013/Weather/*.txt
rm GADGET/data/datasets/manilaFloods2013/GoodsServices/*.txt
rm GADGET/data/datasets/manilaFloods2013/Discussion/*.txt
rm GADGET/data/datasets/manilaFloods2013/Advice/*.txt
rm GADGET/data/datasets/manilaFloods2013/CleanUp/*.txt
rm GADGET/data/datasets/manilaFloods2013/Official/*.txt
rm GADGET/data/datasets/manilaFloods2013/Factoid/*.txt
rm GADGET/data/datasets/manilaFloods2013/Irrelevant/*.txt
rm GADGET/data/datasets/manilaFloods2013/PastNews/*.txt
rm GADGET/data/datasets/manilaFloods2013/Hashtags/*.txt
rm GADGET/data/datasets/manilaFloods2013/SearchAndRescue/*.txt
rm GADGET/data/datasets/manilaFloods2013/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/manilaFloods2013/MovePeople/*.txt
rm GADGET/data/datasets/manilaFloods2013/Donations/*.txt
rm GADGET/data/datasets/manilaFloods2013/EmergingThreats/*.txt
rm GADGET/data/datasets/manilaFloods2013/ServiceAvailable/*.txt
rm GADGET/data/datasets/manilaFloods2013/ContinuingNews/*.txt
rm GADGET/data/datasets/manilaFloods2013/Volunteer/*.txt
rm GADGET/data/datasets/manilaFloods2013/Unknown/*.txt
rm GADGET/data/datasets/manilaFloods2013/Sentiment/*.txt
rm GADGET/data/datasets/manilaFloods2013/SignificantEventChange/*.txt
rm GADGET/data/datasets/manilaFloods2013/FirstPartyObservation/*.txt
rm GADGET/data/datasets/manilaFloods2013/MultimediaShare/*.txt
rm GADGET/data/datasets/manilaFloods2013/KnownAlready/*.txt
rm GADGET/data/datasets/Tornado_features/InformationWanted/*.txt
rm GADGET/data/datasets/Tornado_features/Weather/*.txt
rm GADGET/data/datasets/Tornado_features/GoodsServices/*.txt
rm GADGET/data/datasets/Tornado_features/Discussion/*.txt
rm GADGET/data/datasets/Tornado_features/Advice/*.txt
rm GADGET/data/datasets/Tornado_features/CleanUp/*.txt
rm GADGET/data/datasets/Tornado_features/Official/*.txt
rm GADGET/data/datasets/Tornado_features/Factoid/*.txt
rm GADGET/data/datasets/Tornado_features/Irrelevant/*.txt
rm GADGET/data/datasets/Tornado_features/Hashtags/*.txt
rm GADGET/data/datasets/Tornado_features/SearchAndRescue/*.txt
rm GADGET/data/datasets/Tornado_features/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/Tornado_features/MovePeople/*.txt
rm GADGET/data/datasets/Tornado_features/Donations/*.txt
rm GADGET/data/datasets/Tornado_features/EmergingThreats/*.txt
rm GADGET/data/datasets/Tornado_features/ServiceAvailable/*.txt
rm GADGET/data/datasets/Tornado_features/ContinuingNews/*.txt
rm GADGET/data/datasets/Tornado_features/Volunteer/*.txt
rm GADGET/data/datasets/Tornado_features/Unknown/*.txt
rm GADGET/data/datasets/Tornado_features/Sentiment/*.txt
rm GADGET/data/datasets/Tornado_features/SignificantEventChange/*.txt
rm GADGET/data/datasets/Tornado_features/FirstPartyObservation/*.txt
rm GADGET/data/datasets/Tornado_features/MultimediaShare/*.txt
rm GADGET/data/datasets/Shooting_features/InformationWanted/*.txt
rm GADGET/data/datasets/Shooting_features/Discussion/*.txt
rm GADGET/data/datasets/Shooting_features/Advice/*.txt
rm GADGET/data/datasets/Shooting_features/CleanUp/*.txt
rm GADGET/data/datasets/Shooting_features/Factoid/*.txt
rm GADGET/data/datasets/Shooting_features/Irrelevant/*.txt
rm GADGET/data/datasets/Shooting_features/PastNews/*.txt
rm GADGET/data/datasets/Shooting_features/Hashtags/*.txt
rm GADGET/data/datasets/Shooting_features/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/Shooting_features/Donations/*.txt
rm GADGET/data/datasets/Shooting_features/EmergingThreats/*.txt
rm GADGET/data/datasets/Shooting_features/ContinuingNews/*.txt
rm GADGET/data/datasets/Shooting_features/Volunteer/*.txt
rm GADGET/data/datasets/Shooting_features/Sentiment/*.txt
rm GADGET/data/datasets/Shooting_features/FirstPartyObservation/*.txt
rm GADGET/data/datasets/Shooting_features/MultimediaShare/*.txt
rm GADGET/data/datasets/Shooting_features/KnownAlready/*.txt
rm GADGET/data/datasets/chileEarthquake2014/InformationWanted/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Weather/*.txt
rm GADGET/data/datasets/chileEarthquake2014/GoodsServices/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Discussion/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Advice/*.txt
rm GADGET/data/datasets/chileEarthquake2014/CleanUp/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Official/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Factoid/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Irrelevant/*.txt
rm GADGET/data/datasets/chileEarthquake2014/PastNews/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Hashtags/*.txt
rm GADGET/data/datasets/chileEarthquake2014/SearchAndRescue/*.txt
rm GADGET/data/datasets/chileEarthquake2014/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/chileEarthquake2014/MovePeople/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Donations/*.txt
rm GADGET/data/datasets/chileEarthquake2014/EmergingThreats/*.txt
rm GADGET/data/datasets/chileEarthquake2014/ServiceAvailable/*.txt
rm GADGET/data/datasets/chileEarthquake2014/ContinuingNews/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Volunteer/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Unknown/*.txt
rm GADGET/data/datasets/chileEarthquake2014/Sentiment/*.txt
rm GADGET/data/datasets/chileEarthquake2014/SignificantEventChange/*.txt
rm GADGET/data/datasets/chileEarthquake2014/FirstPartyObservation/*.txt
rm GADGET/data/datasets/chileEarthquake2014/MultimediaShare/*.txt
rm GADGET/data/datasets/chileEarthquake2014/KnownAlready/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/InformationWanted/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Weather/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/GoodsServices/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Discussion/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Advice/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/CleanUp/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Official/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Factoid/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Irrelevant/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/PastNews/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Hashtags/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/SearchAndRescue/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/MovePeople/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Donations/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/EmergingThreats/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/ServiceAvailable/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/ContinuingNews/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Volunteer/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Unknown/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/Sentiment/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/SignificantEventChange/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/FirstPartyObservation/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/MultimediaShare/*.txt
rm GADGET/data/datasets/philipinnesFloods2012/KnownAlready/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/InformationWanted/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Weather/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/GoodsServices/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Discussion/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Advice/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/CleanUp/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Official/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Factoid/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Irrelevant/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/PastNews/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Hashtags/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/SearchAndRescue/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/MovePeople/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Donations/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/EmergingThreats/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/ServiceAvailable/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/ContinuingNews/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Volunteer/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Unknown/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/Sentiment/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/SignificantEventChange/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/FirstPartyObservation/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/MultimediaShare/*.txt
rm GADGET/data/datasets/typhoonYolanda2013/KnownAlready/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/InformationWanted/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Weather/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/GoodsServices/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Discussion/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Advice/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/CleanUp/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Official/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Factoid/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Irrelevant/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/PastNews/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Hashtags/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/SearchAndRescue/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/MovePeople/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Donations/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/EmergingThreats/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/ServiceAvailable/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/ContinuingNews/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Volunteer/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Unknown/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/Sentiment/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/SignificantEventChange/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/FirstPartyObservation/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/MultimediaShare/*.txt
rm GADGET/data/datasets/italyEarthquakes2012/KnownAlready/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/InformationWanted/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Weather/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/GoodsServices/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Discussion/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Advice/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/CleanUp/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Official/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Factoid/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Irrelevant/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/PastNews/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Hashtags/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/SearchAndRescue/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/ThirdPartyObservation/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/MovePeople/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Donations/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/EmergingThreats/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/ServiceAvailable/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/ContinuingNews/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Volunteer/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Unknown/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/Sentiment/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/SignificantEventChange/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/FirstPartyObservation/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/MultimediaShare/*.txt
rm GADGET/data/datasets/typhoonHagupit2014/KnownAlready/*.txt
