#!/bin/bash
rm GADGET/data/datasets/albertaFloods2013/InformationWanted/*.dat
rm GADGET/data/datasets/albertaFloods2013/Weather/*.dat
rm GADGET/data/datasets/albertaFloods2013/GoodsServices/*.dat
rm GADGET/data/datasets/albertaFloods2013/Discussion/*.dat
rm GADGET/data/datasets/albertaFloods2013/Advice/*.dat
rm GADGET/data/datasets/albertaFloods2013/CleanUp/*.dat
rm GADGET/data/datasets/albertaFloods2013/Official/*.dat
rm GADGET/data/datasets/albertaFloods2013/Factoid/*.dat
rm GADGET/data/datasets/albertaFloods2013/Irrelevant/*.dat
rm GADGET/data/datasets/albertaFloods2013/PastNews/*.dat
rm GADGET/data/datasets/albertaFloods2013/Hashtags/*.dat
rm GADGET/data/datasets/albertaFloods2013/SearchAndRescue/*.dat
rm GADGET/data/datasets/albertaFloods2013/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/albertaFloods2013/MovePeople/*.dat
rm GADGET/data/datasets/albertaFloods2013/Donations/*.dat
rm GADGET/data/datasets/albertaFloods2013/EmergingThreats/*.dat
rm GADGET/data/datasets/albertaFloods2013/ServiceAvailable/*.dat
rm GADGET/data/datasets/albertaFloods2013/ContinuingNews/*.dat
rm GADGET/data/datasets/albertaFloods2013/Volunteer/*.dat
rm GADGET/data/datasets/albertaFloods2013/Unknown/*.dat
rm GADGET/data/datasets/albertaFloods2013/Sentiment/*.dat
rm GADGET/data/datasets/albertaFloods2013/SignificantEventChange/*.dat
rm GADGET/data/datasets/albertaFloods2013/FirstPartyObservation/*.dat
rm GADGET/data/datasets/albertaFloods2013/MultimediaShare/*.dat
rm GADGET/data/datasets/albertaFloods2013/KnownAlready/*.dat
rm GADGET/data/datasets/queenslandFloods2013/InformationWanted/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Weather/*.dat
rm GADGET/data/datasets/queenslandFloods2013/GoodsServices/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Discussion/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Advice/*.dat
rm GADGET/data/datasets/queenslandFloods2013/CleanUp/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Official/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Factoid/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Irrelevant/*.dat
rm GADGET/data/datasets/queenslandFloods2013/PastNews/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Hashtags/*.dat
rm GADGET/data/datasets/queenslandFloods2013/SearchAndRescue/*.dat
rm GADGET/data/datasets/queenslandFloods2013/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/queenslandFloods2013/MovePeople/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Donations/*.dat
rm GADGET/data/datasets/queenslandFloods2013/EmergingThreats/*.dat
rm GADGET/data/datasets/queenslandFloods2013/ServiceAvailable/*.dat
rm GADGET/data/datasets/queenslandFloods2013/ContinuingNews/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Volunteer/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Unknown/*.dat
rm GADGET/data/datasets/queenslandFloods2013/Sentiment/*.dat
rm GADGET/data/datasets/queenslandFloods2013/SignificantEventChange/*.dat
rm GADGET/data/datasets/queenslandFloods2013/FirstPartyObservation/*.dat
rm GADGET/data/datasets/queenslandFloods2013/MultimediaShare/*.dat
rm GADGET/data/datasets/queenslandFloods2013/KnownAlready/*.dat
rm GADGET/data/datasets/Bombing_features/InformationWanted/*.dat
rm GADGET/data/datasets/Bombing_features/GoodsServices/*.dat
rm GADGET/data/datasets/Bombing_features/Discussion/*.dat
rm GADGET/data/datasets/Bombing_features/Advice/*.dat
rm GADGET/data/datasets/Bombing_features/Official/*.dat
rm GADGET/data/datasets/Bombing_features/Factoid/*.dat
rm GADGET/data/datasets/Bombing_features/Irrelevant/*.dat
rm GADGET/data/datasets/Bombing_features/PastNews/*.dat
rm GADGET/data/datasets/Bombing_features/Hashtags/*.dat
rm GADGET/data/datasets/Bombing_features/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/Bombing_features/Donations/*.dat
rm GADGET/data/datasets/Bombing_features/EmergingThreats/*.dat
rm GADGET/data/datasets/Bombing_features/ServiceAvailable/*.dat
rm GADGET/data/datasets/Bombing_features/ContinuingNews/*.dat
rm GADGET/data/datasets/Bombing_features/Volunteer/*.dat
rm GADGET/data/datasets/Bombing_features/Sentiment/*.dat
rm GADGET/data/datasets/Bombing_features/SignificantEventChange/*.dat
rm GADGET/data/datasets/Bombing_features/FirstPartyObservation/*.dat
rm GADGET/data/datasets/Bombing_features/MultimediaShare/*.dat
rm GADGET/data/datasets/Bombing_features/KnownAlready/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/InformationWanted/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Weather/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/GoodsServices/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Discussion/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Advice/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/CleanUp/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Official/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Factoid/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Irrelevant/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/PastNews/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Hashtags/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/SearchAndRescue/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/MovePeople/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Donations/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/EmergingThreats/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/ServiceAvailable/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/ContinuingNews/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Volunteer/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Unknown/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/Sentiment/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/SignificantEventChange/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/FirstPartyObservation/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/MultimediaShare/*.dat
rm GADGET/data/datasets/guatemalaEarthquake2012/KnownAlready/*.dat
rm GADGET/data/datasets/fire_features/InformationWanted/*.dat
rm GADGET/data/datasets/fire_features/Weather/*.dat
rm GADGET/data/datasets/fire_features/Discussion/*.dat
rm GADGET/data/datasets/fire_features/Advice/*.dat
rm GADGET/data/datasets/fire_features/Official/*.dat
rm GADGET/data/datasets/fire_features/Factoid/*.dat
rm GADGET/data/datasets/fire_features/Irrelevant/*.dat
rm GADGET/data/datasets/fire_features/PastNews/*.dat
rm GADGET/data/datasets/fire_features/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/fire_features/MovePeople/*.dat
rm GADGET/data/datasets/fire_features/Donations/*.dat
rm GADGET/data/datasets/fire_features/EmergingThreats/*.dat
rm GADGET/data/datasets/fire_features/ServiceAvailable/*.dat
rm GADGET/data/datasets/fire_features/ContinuingNews/*.dat
rm GADGET/data/datasets/fire_features/Volunteer/*.dat
rm GADGET/data/datasets/fire_features/Sentiment/*.dat
rm GADGET/data/datasets/fire_features/SignificantEventChange/*.dat
rm GADGET/data/datasets/fire_features/FirstPartyObservation/*.dat
rm GADGET/data/datasets/fire_features/MultimediaShare/*.dat
rm GADGET/data/datasets/fire_features/KnownAlready/*.dat
rm GADGET/data/datasets/Attacks_features/Discussion/*.dat
rm GADGET/data/datasets/Attacks_features/Advice/*.dat
rm GADGET/data/datasets/Attacks_features/Official/*.dat
rm GADGET/data/datasets/Attacks_features/Factoid/*.dat
rm GADGET/data/datasets/Attacks_features/Irrelevant/*.dat
rm GADGET/data/datasets/Attacks_features/Hashtags/*.dat
rm GADGET/data/datasets/Attacks_features/SearchAndRescue/*.dat
rm GADGET/data/datasets/Attacks_features/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/Attacks_features/EmergingThreats/*.dat
rm GADGET/data/datasets/Attacks_features/ServiceAvailable/*.dat
rm GADGET/data/datasets/Attacks_features/ContinuingNews/*.dat
rm GADGET/data/datasets/Attacks_features/Unknown/*.dat
rm GADGET/data/datasets/Attacks_features/Sentiment/*.dat
rm GADGET/data/datasets/Attacks_features/SignificantEventChange/*.dat
rm GADGET/data/datasets/Attacks_features/FirstPartyObservation/*.dat
rm GADGET/data/datasets/Attacks_features/MultimediaShare/*.dat
rm GADGET/data/datasets/Attacks_features/KnownAlready/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/InformationWanted/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Weather/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/GoodsServices/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Discussion/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Advice/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/CleanUp/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Official/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Factoid/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Irrelevant/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/PastNews/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Hashtags/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/SearchAndRescue/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/MovePeople/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Donations/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/EmergingThreats/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/ServiceAvailable/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/ContinuingNews/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Volunteer/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Unknown/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/Sentiment/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/SignificantEventChange/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/FirstPartyObservation/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/MultimediaShare/*.dat
rm GADGET/data/datasets/nepalEarthquake2015/KnownAlready/*.dat
rm GADGET/data/datasets/manilaFloods2013/InformationWanted/*.dat
rm GADGET/data/datasets/manilaFloods2013/Weather/*.dat
rm GADGET/data/datasets/manilaFloods2013/GoodsServices/*.dat
rm GADGET/data/datasets/manilaFloods2013/Discussion/*.dat
rm GADGET/data/datasets/manilaFloods2013/Advice/*.dat
rm GADGET/data/datasets/manilaFloods2013/CleanUp/*.dat
rm GADGET/data/datasets/manilaFloods2013/Official/*.dat
rm GADGET/data/datasets/manilaFloods2013/Factoid/*.dat
rm GADGET/data/datasets/manilaFloods2013/Irrelevant/*.dat
rm GADGET/data/datasets/manilaFloods2013/PastNews/*.dat
rm GADGET/data/datasets/manilaFloods2013/Hashtags/*.dat
rm GADGET/data/datasets/manilaFloods2013/SearchAndRescue/*.dat
rm GADGET/data/datasets/manilaFloods2013/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/manilaFloods2013/MovePeople/*.dat
rm GADGET/data/datasets/manilaFloods2013/Donations/*.dat
rm GADGET/data/datasets/manilaFloods2013/EmergingThreats/*.dat
rm GADGET/data/datasets/manilaFloods2013/ServiceAvailable/*.dat
rm GADGET/data/datasets/manilaFloods2013/ContinuingNews/*.dat
rm GADGET/data/datasets/manilaFloods2013/Volunteer/*.dat
rm GADGET/data/datasets/manilaFloods2013/Unknown/*.dat
rm GADGET/data/datasets/manilaFloods2013/Sentiment/*.dat
rm GADGET/data/datasets/manilaFloods2013/SignificantEventChange/*.dat
rm GADGET/data/datasets/manilaFloods2013/FirstPartyObservation/*.dat
rm GADGET/data/datasets/manilaFloods2013/MultimediaShare/*.dat
rm GADGET/data/datasets/manilaFloods2013/KnownAlready/*.dat
rm GADGET/data/datasets/Tornado_features/InformationWanted/*.dat
rm GADGET/data/datasets/Tornado_features/Weather/*.dat
rm GADGET/data/datasets/Tornado_features/GoodsServices/*.dat
rm GADGET/data/datasets/Tornado_features/Discussion/*.dat
rm GADGET/data/datasets/Tornado_features/Advice/*.dat
rm GADGET/data/datasets/Tornado_features/CleanUp/*.dat
rm GADGET/data/datasets/Tornado_features/Official/*.dat
rm GADGET/data/datasets/Tornado_features/Factoid/*.dat
rm GADGET/data/datasets/Tornado_features/Irrelevant/*.dat
rm GADGET/data/datasets/Tornado_features/Hashtags/*.dat
rm GADGET/data/datasets/Tornado_features/SearchAndRescue/*.dat
rm GADGET/data/datasets/Tornado_features/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/Tornado_features/MovePeople/*.dat
rm GADGET/data/datasets/Tornado_features/Donations/*.dat
rm GADGET/data/datasets/Tornado_features/EmergingThreats/*.dat
rm GADGET/data/datasets/Tornado_features/ServiceAvailable/*.dat
rm GADGET/data/datasets/Tornado_features/ContinuingNews/*.dat
rm GADGET/data/datasets/Tornado_features/Volunteer/*.dat
rm GADGET/data/datasets/Tornado_features/Unknown/*.dat
rm GADGET/data/datasets/Tornado_features/Sentiment/*.dat
rm GADGET/data/datasets/Tornado_features/SignificantEventChange/*.dat
rm GADGET/data/datasets/Tornado_features/FirstPartyObservation/*.dat
rm GADGET/data/datasets/Tornado_features/MultimediaShare/*.dat
rm GADGET/data/datasets/Shooting_features/InformationWanted/*.dat
rm GADGET/data/datasets/Shooting_features/Discussion/*.dat
rm GADGET/data/datasets/Shooting_features/Advice/*.dat
rm GADGET/data/datasets/Shooting_features/CleanUp/*.dat
rm GADGET/data/datasets/Shooting_features/Factoid/*.dat
rm GADGET/data/datasets/Shooting_features/Irrelevant/*.dat
rm GADGET/data/datasets/Shooting_features/PastNews/*.dat
rm GADGET/data/datasets/Shooting_features/Hashtags/*.dat
rm GADGET/data/datasets/Shooting_features/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/Shooting_features/Donations/*.dat
rm GADGET/data/datasets/Shooting_features/EmergingThreats/*.dat
rm GADGET/data/datasets/Shooting_features/ContinuingNews/*.dat
rm GADGET/data/datasets/Shooting_features/Volunteer/*.dat
rm GADGET/data/datasets/Shooting_features/Sentiment/*.dat
rm GADGET/data/datasets/Shooting_features/FirstPartyObservation/*.dat
rm GADGET/data/datasets/Shooting_features/MultimediaShare/*.dat
rm GADGET/data/datasets/Shooting_features/KnownAlready/*.dat
rm GADGET/data/datasets/chileEarthquake2014/InformationWanted/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Weather/*.dat
rm GADGET/data/datasets/chileEarthquake2014/GoodsServices/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Discussion/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Advice/*.dat
rm GADGET/data/datasets/chileEarthquake2014/CleanUp/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Official/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Factoid/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Irrelevant/*.dat
rm GADGET/data/datasets/chileEarthquake2014/PastNews/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Hashtags/*.dat
rm GADGET/data/datasets/chileEarthquake2014/SearchAndRescue/*.dat
rm GADGET/data/datasets/chileEarthquake2014/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/chileEarthquake2014/MovePeople/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Donations/*.dat
rm GADGET/data/datasets/chileEarthquake2014/EmergingThreats/*.dat
rm GADGET/data/datasets/chileEarthquake2014/ServiceAvailable/*.dat
rm GADGET/data/datasets/chileEarthquake2014/ContinuingNews/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Volunteer/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Unknown/*.dat
rm GADGET/data/datasets/chileEarthquake2014/Sentiment/*.dat
rm GADGET/data/datasets/chileEarthquake2014/SignificantEventChange/*.dat
rm GADGET/data/datasets/chileEarthquake2014/FirstPartyObservation/*.dat
rm GADGET/data/datasets/chileEarthquake2014/MultimediaShare/*.dat
rm GADGET/data/datasets/chileEarthquake2014/KnownAlready/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/InformationWanted/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Weather/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/GoodsServices/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Discussion/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Advice/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/CleanUp/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Official/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Factoid/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Irrelevant/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/PastNews/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Hashtags/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/SearchAndRescue/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/MovePeople/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Donations/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/EmergingThreats/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/ServiceAvailable/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/ContinuingNews/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Volunteer/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Unknown/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/Sentiment/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/SignificantEventChange/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/FirstPartyObservation/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/MultimediaShare/*.dat
rm GADGET/data/datasets/philipinnesFloods2012/KnownAlready/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/InformationWanted/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Weather/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/GoodsServices/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Discussion/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Advice/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/CleanUp/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Official/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Factoid/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Irrelevant/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/PastNews/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Hashtags/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/SearchAndRescue/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/MovePeople/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Donations/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/EmergingThreats/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/ServiceAvailable/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/ContinuingNews/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Volunteer/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Unknown/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/Sentiment/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/SignificantEventChange/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/FirstPartyObservation/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/MultimediaShare/*.dat
rm GADGET/data/datasets/typhoonYolanda2013/KnownAlready/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/InformationWanted/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Weather/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/GoodsServices/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Discussion/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Advice/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/CleanUp/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Official/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Factoid/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Irrelevant/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/PastNews/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Hashtags/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/SearchAndRescue/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/MovePeople/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Donations/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/EmergingThreats/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/ServiceAvailable/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/ContinuingNews/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Volunteer/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Unknown/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/Sentiment/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/SignificantEventChange/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/FirstPartyObservation/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/MultimediaShare/*.dat
rm GADGET/data/datasets/italyEarthquakes2012/KnownAlready/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/InformationWanted/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Weather/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/GoodsServices/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Discussion/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Advice/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/CleanUp/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Official/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Factoid/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Irrelevant/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/PastNews/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Hashtags/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/SearchAndRescue/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/ThirdPartyObservation/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/MovePeople/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Donations/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/EmergingThreats/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/ServiceAvailable/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/ContinuingNews/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Volunteer/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Unknown/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/Sentiment/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/SignificantEventChange/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/FirstPartyObservation/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/MultimediaShare/*.dat
rm GADGET/data/datasets/typhoonHagupit2014/KnownAlready/*.dat
