#!/bin/bash
##SBATCH --partition=debug --qos=debug
#SBATCH --partition=general-compute --qos=general-compute
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=128000
#SBATCH --job-name="covpeg0"
#SBATCH --output=cov-pegasos0.out
#SBATCH --mail-user=nitinnat@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue
#SBATCH --exclusive
#SBATCH --constraint="CPU-E5-2660"
##Specifies that the job will be requeued after a node failure.
##The default is that the job will not be requeued.

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR


ulimit -s unlimited
#
java -jar ../cent_pegasos_oaat_5.jar /projects/academic/haimonti/Pegasos4/GadgetStaticOAAT/data/covertype/covertype-train /projects/academic/haimonti/Pegasos4/GadgetStaticOAAT/data/covertype/covertype-test 0.000001 1000000 0 54
#
echo "All Done!"
