#!/bin/bash


python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file t_0.dat

python one_dp_per_file.py --datafolder data --dataset ccat --file tst_0.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_1.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_2.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_3.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_4.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_5.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_6.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_7.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_8.dat
python one_dp_per_file.py --datafolder data --dataset ccat --file tst_9.dat