#!/bin/bash
##SBATCH --partition=debug
#SBATCH --partition=largemem --qos=largemem
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
##SBATCH --mem=512000
#SBATCH --job-name="P_ccat"
#SBATCH --output=ccat-pegasos.out
#SBATCH --mail-user=nitinnat@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue
#SBATCH --exclusive
##SBATCH --constraint="CPU-E7-4830"
##Specifies that the job will be requeued after a node failure.
##The default is that the job will not be requeued.

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR


ulimit -s unlimited
#
free -m
java -Xmx256000m -Xms1024m -Xss1024m -jar ../cent_pegasos.jar ../data/ccat/ccat-train.dat ../data/ccat/ccat-test.dat 0.0001 10000000000 0
#
echo "All Done!"
