%!/bin/bash

python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset InformationWanted --trainfile InformationWanted_train_2700.txt --testfile InformationWanted_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Weather --trainfile Weather_train_2700.txt --testfile Weather_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset GoodsServices --trainfile GoodsServices_train_2700.txt --testfile GoodsServices_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Discussion --trainfile Discussion_train_2700.txt --testfile Discussion_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Advice --trainfile Advice_train_2700.txt --testfile Advice_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset CleanUp --trainfile CleanUp_train_2700.txt --testfile CleanUp_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Official --trainfile Official_train_2700.txt --testfile Official_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Factoid --trainfile Factoid_train_2700.txt --testfile Factoid_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Irrelevant --trainfile Irrelevant_train_2700.txt --testfile Irrelevant_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset PastNews --trainfile PastNews_train_2700.txt --testfile PastNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Hashtags --trainfile Hashtags_train_2700.txt --testfile Hashtags_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2700.txt --testfile SearchAndRescue_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2700.txt --testfile ThirdPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset MovePeople --trainfile MovePeople_train_2700.txt --testfile MovePeople_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Donations --trainfile Donations_train_2700.txt --testfile Donations_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset EmergingThreats --trainfile EmergingThreats_train_2700.txt --testfile EmergingThreats_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2700.txt --testfile ServiceAvailable_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset ContinuingNews --trainfile ContinuingNews_train_2700.txt --testfile ContinuingNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Volunteer --trainfile Volunteer_train_2700.txt --testfile Volunteer_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Unknown --trainfile Unknown_train_2700.txt --testfile Unknown_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset Sentiment --trainfile Sentiment_train_2700.txt --testfile Sentiment_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2700.txt --testfile SignificantEventChange_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2700.txt --testfile FirstPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset MultimediaShare --trainfile MultimediaShare_train_2700.txt --testfile MultimediaShare_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/albertaFloods2013 --dataset KnownAlready --trainfile KnownAlready_train_2700.txt --testfile KnownAlready_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset InformationWanted --trainfile InformationWanted_train_2700.txt --testfile InformationWanted_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Weather --trainfile Weather_train_2700.txt --testfile Weather_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset GoodsServices --trainfile GoodsServices_train_2700.txt --testfile GoodsServices_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Discussion --trainfile Discussion_train_2700.txt --testfile Discussion_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Advice --trainfile Advice_train_2700.txt --testfile Advice_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset CleanUp --trainfile CleanUp_train_2700.txt --testfile CleanUp_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Official --trainfile Official_train_2700.txt --testfile Official_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Factoid --trainfile Factoid_train_2700.txt --testfile Factoid_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Irrelevant --trainfile Irrelevant_train_2700.txt --testfile Irrelevant_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset PastNews --trainfile PastNews_train_2700.txt --testfile PastNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Hashtags --trainfile Hashtags_train_2700.txt --testfile Hashtags_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2700.txt --testfile SearchAndRescue_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2700.txt --testfile ThirdPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset MovePeople --trainfile MovePeople_train_2700.txt --testfile MovePeople_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Donations --trainfile Donations_train_2700.txt --testfile Donations_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset EmergingThreats --trainfile EmergingThreats_train_2700.txt --testfile EmergingThreats_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2700.txt --testfile ServiceAvailable_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset ContinuingNews --trainfile ContinuingNews_train_2700.txt --testfile ContinuingNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Volunteer --trainfile Volunteer_train_2700.txt --testfile Volunteer_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Unknown --trainfile Unknown_train_2700.txt --testfile Unknown_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset Sentiment --trainfile Sentiment_train_2700.txt --testfile Sentiment_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2700.txt --testfile SignificantEventChange_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2700.txt --testfile FirstPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset MultimediaShare --trainfile MultimediaShare_train_2700.txt --testfile MultimediaShare_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/queenslandFloods2013 --dataset KnownAlready --trainfile KnownAlready_train_2700.txt --testfile KnownAlready_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset InformationWanted --trainfile InformationWanted_train_2800.txt --testfile InformationWanted_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset GoodsServices --trainfile GoodsServices_train_2800.txt --testfile GoodsServices_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Discussion --trainfile Discussion_train_2800.txt --testfile Discussion_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Advice --trainfile Advice_train_2800.txt --testfile Advice_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Official --trainfile Official_train_2800.txt --testfile Official_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Factoid --trainfile Factoid_train_2800.txt --testfile Factoid_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Irrelevant --trainfile Irrelevant_train_2800.txt --testfile Irrelevant_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset PastNews --trainfile PastNews_train_2800.txt --testfile PastNews_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Hashtags --trainfile Hashtags_train_2800.txt --testfile Hashtags_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2800.txt --testfile ThirdPartyObservation_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Donations --trainfile Donations_train_2800.txt --testfile Donations_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset EmergingThreats --trainfile EmergingThreats_train_2800.txt --testfile EmergingThreats_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset ServiceAvailable --trainfile ServiceAvailable_train_2800.txt --testfile ServiceAvailable_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset ContinuingNews --trainfile ContinuingNews_train_2800.txt --testfile ContinuingNews_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Volunteer --trainfile Volunteer_train_2800.txt --testfile Volunteer_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset Sentiment --trainfile Sentiment_train_2800.txt --testfile Sentiment_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset SignificantEventChange --trainfile SignificantEventChange_train_2800.txt --testfile SignificantEventChange_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2800.txt --testfile FirstPartyObservation_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset MultimediaShare --trainfile MultimediaShare_train_2800.txt --testfile MultimediaShare_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Bombing_features --dataset KnownAlready --trainfile KnownAlready_train_2800.txt --testfile KnownAlready_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset InformationWanted --trainfile InformationWanted_train_2600.txt --testfile InformationWanted_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Weather --trainfile Weather_train_2600.txt --testfile Weather_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset GoodsServices --trainfile GoodsServices_train_2600.txt --testfile GoodsServices_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Discussion --trainfile Discussion_train_2600.txt --testfile Discussion_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Advice --trainfile Advice_train_2600.txt --testfile Advice_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset CleanUp --trainfile CleanUp_train_2600.txt --testfile CleanUp_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Official --trainfile Official_train_2600.txt --testfile Official_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Factoid --trainfile Factoid_train_2600.txt --testfile Factoid_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Irrelevant --trainfile Irrelevant_train_2600.txt --testfile Irrelevant_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset PastNews --trainfile PastNews_train_2600.txt --testfile PastNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Hashtags --trainfile Hashtags_train_2600.txt --testfile Hashtags_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2600.txt --testfile SearchAndRescue_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2600.txt --testfile ThirdPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset MovePeople --trainfile MovePeople_train_2600.txt --testfile MovePeople_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Donations --trainfile Donations_train_2600.txt --testfile Donations_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset EmergingThreats --trainfile EmergingThreats_train_2600.txt --testfile EmergingThreats_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2600.txt --testfile ServiceAvailable_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset ContinuingNews --trainfile ContinuingNews_train_2600.txt --testfile ContinuingNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Volunteer --trainfile Volunteer_train_2600.txt --testfile Volunteer_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Unknown --trainfile Unknown_train_2600.txt --testfile Unknown_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset Sentiment --trainfile Sentiment_train_2600.txt --testfile Sentiment_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2600.txt --testfile SignificantEventChange_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2600.txt --testfile FirstPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset MultimediaShare --trainfile MultimediaShare_train_2600.txt --testfile MultimediaShare_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/guatemalaEarthquake2012 --dataset KnownAlready --trainfile KnownAlready_train_2600.txt --testfile KnownAlready_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset InformationWanted --trainfile InformationWanted_train_2700.txt --testfile InformationWanted_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Weather --trainfile Weather_train_2700.txt --testfile Weather_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Discussion --trainfile Discussion_train_2700.txt --testfile Discussion_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Advice --trainfile Advice_train_2700.txt --testfile Advice_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Official --trainfile Official_train_2700.txt --testfile Official_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Factoid --trainfile Factoid_train_2700.txt --testfile Factoid_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Irrelevant --trainfile Irrelevant_train_2700.txt --testfile Irrelevant_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset PastNews --trainfile PastNews_train_2700.txt --testfile PastNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2700.txt --testfile ThirdPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset MovePeople --trainfile MovePeople_train_2700.txt --testfile MovePeople_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Donations --trainfile Donations_train_2700.txt --testfile Donations_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset EmergingThreats --trainfile EmergingThreats_train_2700.txt --testfile EmergingThreats_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset ServiceAvailable --trainfile ServiceAvailable_train_2700.txt --testfile ServiceAvailable_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset ContinuingNews --trainfile ContinuingNews_train_2700.txt --testfile ContinuingNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Volunteer --trainfile Volunteer_train_2700.txt --testfile Volunteer_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset Sentiment --trainfile Sentiment_train_2700.txt --testfile Sentiment_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset SignificantEventChange --trainfile SignificantEventChange_train_2700.txt --testfile SignificantEventChange_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2700.txt --testfile FirstPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset MultimediaShare --trainfile MultimediaShare_train_2700.txt --testfile MultimediaShare_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/fire_features --dataset KnownAlready --trainfile KnownAlready_train_2700.txt --testfile KnownAlready_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Discussion --trainfile Discussion_train_2800.txt --testfile Discussion_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Advice --trainfile Advice_train_2800.txt --testfile Advice_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Official --trainfile Official_train_2800.txt --testfile Official_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Factoid --trainfile Factoid_train_2800.txt --testfile Factoid_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Irrelevant --trainfile Irrelevant_train_2800.txt --testfile Irrelevant_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Hashtags --trainfile Hashtags_train_2800.txt --testfile Hashtags_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset SearchAndRescue --trainfile SearchAndRescue_train_2800.txt --testfile SearchAndRescue_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2800.txt --testfile ThirdPartyObservation_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset EmergingThreats --trainfile EmergingThreats_train_2800.txt --testfile EmergingThreats_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset ServiceAvailable --trainfile ServiceAvailable_train_2800.txt --testfile ServiceAvailable_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset ContinuingNews --trainfile ContinuingNews_train_2800.txt --testfile ContinuingNews_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Unknown --trainfile Unknown_train_2800.txt --testfile Unknown_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset Sentiment --trainfile Sentiment_train_2800.txt --testfile Sentiment_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset SignificantEventChange --trainfile SignificantEventChange_train_2800.txt --testfile SignificantEventChange_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2800.txt --testfile FirstPartyObservation_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset MultimediaShare --trainfile MultimediaShare_train_2800.txt --testfile MultimediaShare_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/Attacks_features --dataset KnownAlready --trainfile KnownAlready_train_2800.txt --testfile KnownAlready_test_2800.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset InformationWanted --trainfile InformationWanted_train_3200.txt --testfile InformationWanted_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Weather --trainfile Weather_train_3200.txt --testfile Weather_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset GoodsServices --trainfile GoodsServices_train_3200.txt --testfile GoodsServices_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Discussion --trainfile Discussion_train_3200.txt --testfile Discussion_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Advice --trainfile Advice_train_3200.txt --testfile Advice_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset CleanUp --trainfile CleanUp_train_3200.txt --testfile CleanUp_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Official --trainfile Official_train_3200.txt --testfile Official_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Factoid --trainfile Factoid_train_3200.txt --testfile Factoid_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Irrelevant --trainfile Irrelevant_train_3200.txt --testfile Irrelevant_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset PastNews --trainfile PastNews_train_3200.txt --testfile PastNews_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Hashtags --trainfile Hashtags_train_3200.txt --testfile Hashtags_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset SearchAndRescue --trainfile SearchAndRescue_train_3200.txt --testfile SearchAndRescue_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_3200.txt --testfile ThirdPartyObservation_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset MovePeople --trainfile MovePeople_train_3200.txt --testfile MovePeople_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Donations --trainfile Donations_train_3200.txt --testfile Donations_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset EmergingThreats --trainfile EmergingThreats_train_3200.txt --testfile EmergingThreats_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset ServiceAvailable --trainfile ServiceAvailable_train_3200.txt --testfile ServiceAvailable_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset ContinuingNews --trainfile ContinuingNews_train_3200.txt --testfile ContinuingNews_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Volunteer --trainfile Volunteer_train_3200.txt --testfile Volunteer_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Unknown --trainfile Unknown_train_3200.txt --testfile Unknown_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset Sentiment --trainfile Sentiment_train_3200.txt --testfile Sentiment_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset SignificantEventChange --trainfile SignificantEventChange_train_3200.txt --testfile SignificantEventChange_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_3200.txt --testfile FirstPartyObservation_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset MultimediaShare --trainfile MultimediaShare_train_3200.txt --testfile MultimediaShare_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/nepalEarthquake2015 --dataset KnownAlready --trainfile KnownAlready_train_3200.txt --testfile KnownAlready_test_3200.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset InformationWanted --trainfile InformationWanted_train_2600.txt --testfile InformationWanted_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Weather --trainfile Weather_train_2600.txt --testfile Weather_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset GoodsServices --trainfile GoodsServices_train_2600.txt --testfile GoodsServices_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Discussion --trainfile Discussion_train_2600.txt --testfile Discussion_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Advice --trainfile Advice_train_2600.txt --testfile Advice_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset CleanUp --trainfile CleanUp_train_2600.txt --testfile CleanUp_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Official --trainfile Official_train_2600.txt --testfile Official_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Factoid --trainfile Factoid_train_2600.txt --testfile Factoid_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Irrelevant --trainfile Irrelevant_train_2600.txt --testfile Irrelevant_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset PastNews --trainfile PastNews_train_2600.txt --testfile PastNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Hashtags --trainfile Hashtags_train_2600.txt --testfile Hashtags_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2600.txt --testfile SearchAndRescue_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2600.txt --testfile ThirdPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset MovePeople --trainfile MovePeople_train_2600.txt --testfile MovePeople_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Donations --trainfile Donations_train_2600.txt --testfile Donations_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset EmergingThreats --trainfile EmergingThreats_train_2600.txt --testfile EmergingThreats_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2600.txt --testfile ServiceAvailable_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset ContinuingNews --trainfile ContinuingNews_train_2600.txt --testfile ContinuingNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Volunteer --trainfile Volunteer_train_2600.txt --testfile Volunteer_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Unknown --trainfile Unknown_train_2600.txt --testfile Unknown_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset Sentiment --trainfile Sentiment_train_2600.txt --testfile Sentiment_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2600.txt --testfile SignificantEventChange_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2600.txt --testfile FirstPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset MultimediaShare --trainfile MultimediaShare_train_2600.txt --testfile MultimediaShare_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/manilaFloods2013 --dataset KnownAlready --trainfile KnownAlready_train_2600.txt --testfile KnownAlready_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset InformationWanted --trainfile InformationWanted_train_2500.txt --testfile InformationWanted_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Weather --trainfile Weather_train_2500.txt --testfile Weather_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset GoodsServices --trainfile GoodsServices_train_2500.txt --testfile GoodsServices_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Discussion --trainfile Discussion_train_2500.txt --testfile Discussion_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Advice --trainfile Advice_train_2500.txt --testfile Advice_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset CleanUp --trainfile CleanUp_train_2500.txt --testfile CleanUp_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Official --trainfile Official_train_2500.txt --testfile Official_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Factoid --trainfile Factoid_train_2500.txt --testfile Factoid_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Irrelevant --trainfile Irrelevant_train_2500.txt --testfile Irrelevant_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Hashtags --trainfile Hashtags_train_2500.txt --testfile Hashtags_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset SearchAndRescue --trainfile SearchAndRescue_train_2500.txt --testfile SearchAndRescue_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2500.txt --testfile ThirdPartyObservation_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset MovePeople --trainfile MovePeople_train_2500.txt --testfile MovePeople_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Donations --trainfile Donations_train_2500.txt --testfile Donations_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset EmergingThreats --trainfile EmergingThreats_train_2500.txt --testfile EmergingThreats_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset ServiceAvailable --trainfile ServiceAvailable_train_2500.txt --testfile ServiceAvailable_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset ContinuingNews --trainfile ContinuingNews_train_2500.txt --testfile ContinuingNews_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Volunteer --trainfile Volunteer_train_2500.txt --testfile Volunteer_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Unknown --trainfile Unknown_train_2500.txt --testfile Unknown_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset Sentiment --trainfile Sentiment_train_2500.txt --testfile Sentiment_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset SignificantEventChange --trainfile SignificantEventChange_train_2500.txt --testfile SignificantEventChange_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2500.txt --testfile FirstPartyObservation_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Tornado_features --dataset MultimediaShare --trainfile MultimediaShare_train_2500.txt --testfile MultimediaShare_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset InformationWanted --trainfile InformationWanted_train_2900.txt --testfile InformationWanted_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Discussion --trainfile Discussion_train_2900.txt --testfile Discussion_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Advice --trainfile Advice_train_2900.txt --testfile Advice_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset CleanUp --trainfile CleanUp_train_2900.txt --testfile CleanUp_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Factoid --trainfile Factoid_train_2900.txt --testfile Factoid_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Irrelevant --trainfile Irrelevant_train_2900.txt --testfile Irrelevant_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset PastNews --trainfile PastNews_train_2900.txt --testfile PastNews_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Hashtags --trainfile Hashtags_train_2900.txt --testfile Hashtags_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2900.txt --testfile ThirdPartyObservation_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Donations --trainfile Donations_train_2900.txt --testfile Donations_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset EmergingThreats --trainfile EmergingThreats_train_2900.txt --testfile EmergingThreats_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset ContinuingNews --trainfile ContinuingNews_train_2900.txt --testfile ContinuingNews_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Volunteer --trainfile Volunteer_train_2900.txt --testfile Volunteer_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset Sentiment --trainfile Sentiment_train_2900.txt --testfile Sentiment_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2900.txt --testfile FirstPartyObservation_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset MultimediaShare --trainfile MultimediaShare_train_2900.txt --testfile MultimediaShare_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/Shooting_features --dataset KnownAlready --trainfile KnownAlready_train_2900.txt --testfile KnownAlready_test_2900.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset InformationWanted --trainfile InformationWanted_train_2600.txt --testfile InformationWanted_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Weather --trainfile Weather_train_2600.txt --testfile Weather_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset GoodsServices --trainfile GoodsServices_train_2600.txt --testfile GoodsServices_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Discussion --trainfile Discussion_train_2600.txt --testfile Discussion_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Advice --trainfile Advice_train_2600.txt --testfile Advice_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset CleanUp --trainfile CleanUp_train_2600.txt --testfile CleanUp_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Official --trainfile Official_train_2600.txt --testfile Official_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Factoid --trainfile Factoid_train_2600.txt --testfile Factoid_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Irrelevant --trainfile Irrelevant_train_2600.txt --testfile Irrelevant_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset PastNews --trainfile PastNews_train_2600.txt --testfile PastNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Hashtags --trainfile Hashtags_train_2600.txt --testfile Hashtags_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2600.txt --testfile SearchAndRescue_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2600.txt --testfile ThirdPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset MovePeople --trainfile MovePeople_train_2600.txt --testfile MovePeople_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Donations --trainfile Donations_train_2600.txt --testfile Donations_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset EmergingThreats --trainfile EmergingThreats_train_2600.txt --testfile EmergingThreats_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2600.txt --testfile ServiceAvailable_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset ContinuingNews --trainfile ContinuingNews_train_2600.txt --testfile ContinuingNews_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Volunteer --trainfile Volunteer_train_2600.txt --testfile Volunteer_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Unknown --trainfile Unknown_train_2600.txt --testfile Unknown_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset Sentiment --trainfile Sentiment_train_2600.txt --testfile Sentiment_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2600.txt --testfile SignificantEventChange_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2600.txt --testfile FirstPartyObservation_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset MultimediaShare --trainfile MultimediaShare_train_2600.txt --testfile MultimediaShare_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/chileEarthquake2014 --dataset KnownAlready --trainfile KnownAlready_train_2600.txt --testfile KnownAlready_test_2600.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset InformationWanted --trainfile InformationWanted_train_2700.txt --testfile InformationWanted_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Weather --trainfile Weather_train_2700.txt --testfile Weather_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset GoodsServices --trainfile GoodsServices_train_2700.txt --testfile GoodsServices_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Discussion --trainfile Discussion_train_2700.txt --testfile Discussion_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Advice --trainfile Advice_train_2700.txt --testfile Advice_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset CleanUp --trainfile CleanUp_train_2700.txt --testfile CleanUp_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Official --trainfile Official_train_2700.txt --testfile Official_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Factoid --trainfile Factoid_train_2700.txt --testfile Factoid_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Irrelevant --trainfile Irrelevant_train_2700.txt --testfile Irrelevant_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset PastNews --trainfile PastNews_train_2700.txt --testfile PastNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Hashtags --trainfile Hashtags_train_2700.txt --testfile Hashtags_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2700.txt --testfile SearchAndRescue_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2700.txt --testfile ThirdPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset MovePeople --trainfile MovePeople_train_2700.txt --testfile MovePeople_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Donations --trainfile Donations_train_2700.txt --testfile Donations_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset EmergingThreats --trainfile EmergingThreats_train_2700.txt --testfile EmergingThreats_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2700.txt --testfile ServiceAvailable_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset ContinuingNews --trainfile ContinuingNews_train_2700.txt --testfile ContinuingNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Volunteer --trainfile Volunteer_train_2700.txt --testfile Volunteer_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Unknown --trainfile Unknown_train_2700.txt --testfile Unknown_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset Sentiment --trainfile Sentiment_train_2700.txt --testfile Sentiment_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2700.txt --testfile SignificantEventChange_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2700.txt --testfile FirstPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset MultimediaShare --trainfile MultimediaShare_train_2700.txt --testfile MultimediaShare_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/philipinnesFloods2012 --dataset KnownAlready --trainfile KnownAlready_train_2700.txt --testfile KnownAlready_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset InformationWanted --trainfile InformationWanted_train_2700.txt --testfile InformationWanted_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Weather --trainfile Weather_train_2700.txt --testfile Weather_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset GoodsServices --trainfile GoodsServices_train_2700.txt --testfile GoodsServices_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Discussion --trainfile Discussion_train_2700.txt --testfile Discussion_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Advice --trainfile Advice_train_2700.txt --testfile Advice_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset CleanUp --trainfile CleanUp_train_2700.txt --testfile CleanUp_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Official --trainfile Official_train_2700.txt --testfile Official_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Factoid --trainfile Factoid_train_2700.txt --testfile Factoid_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Irrelevant --trainfile Irrelevant_train_2700.txt --testfile Irrelevant_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset PastNews --trainfile PastNews_train_2700.txt --testfile PastNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Hashtags --trainfile Hashtags_train_2700.txt --testfile Hashtags_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2700.txt --testfile SearchAndRescue_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2700.txt --testfile ThirdPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset MovePeople --trainfile MovePeople_train_2700.txt --testfile MovePeople_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Donations --trainfile Donations_train_2700.txt --testfile Donations_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset EmergingThreats --trainfile EmergingThreats_train_2700.txt --testfile EmergingThreats_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2700.txt --testfile ServiceAvailable_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset ContinuingNews --trainfile ContinuingNews_train_2700.txt --testfile ContinuingNews_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Volunteer --trainfile Volunteer_train_2700.txt --testfile Volunteer_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Unknown --trainfile Unknown_train_2700.txt --testfile Unknown_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset Sentiment --trainfile Sentiment_train_2700.txt --testfile Sentiment_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2700.txt --testfile SignificantEventChange_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2700.txt --testfile FirstPartyObservation_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset MultimediaShare --trainfile MultimediaShare_train_2700.txt --testfile MultimediaShare_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonYolanda2013 --dataset KnownAlready --trainfile KnownAlready_train_2700.txt --testfile KnownAlready_test_2700.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset InformationWanted --trainfile InformationWanted_train_2500.txt --testfile InformationWanted_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Weather --trainfile Weather_train_2500.txt --testfile Weather_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset GoodsServices --trainfile GoodsServices_train_2500.txt --testfile GoodsServices_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Discussion --trainfile Discussion_train_2500.txt --testfile Discussion_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Advice --trainfile Advice_train_2500.txt --testfile Advice_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset CleanUp --trainfile CleanUp_train_2500.txt --testfile CleanUp_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Official --trainfile Official_train_2500.txt --testfile Official_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Factoid --trainfile Factoid_train_2500.txt --testfile Factoid_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Irrelevant --trainfile Irrelevant_train_2500.txt --testfile Irrelevant_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset PastNews --trainfile PastNews_train_2500.txt --testfile PastNews_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Hashtags --trainfile Hashtags_train_2500.txt --testfile Hashtags_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset SearchAndRescue --trainfile SearchAndRescue_train_2500.txt --testfile SearchAndRescue_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_2500.txt --testfile ThirdPartyObservation_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset MovePeople --trainfile MovePeople_train_2500.txt --testfile MovePeople_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Donations --trainfile Donations_train_2500.txt --testfile Donations_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset EmergingThreats --trainfile EmergingThreats_train_2500.txt --testfile EmergingThreats_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset ServiceAvailable --trainfile ServiceAvailable_train_2500.txt --testfile ServiceAvailable_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset ContinuingNews --trainfile ContinuingNews_train_2500.txt --testfile ContinuingNews_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Volunteer --trainfile Volunteer_train_2500.txt --testfile Volunteer_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Unknown --trainfile Unknown_train_2500.txt --testfile Unknown_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset Sentiment --trainfile Sentiment_train_2500.txt --testfile Sentiment_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset SignificantEventChange --trainfile SignificantEventChange_train_2500.txt --testfile SignificantEventChange_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_2500.txt --testfile FirstPartyObservation_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset MultimediaShare --trainfile MultimediaShare_train_2500.txt --testfile MultimediaShare_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/italyEarthquakes2012 --dataset KnownAlready --trainfile KnownAlready_train_2500.txt --testfile KnownAlready_test_2500.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset InformationWanted --trainfile InformationWanted_train_3100.txt --testfile InformationWanted_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Weather --trainfile Weather_train_3100.txt --testfile Weather_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset GoodsServices --trainfile GoodsServices_train_3100.txt --testfile GoodsServices_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Discussion --trainfile Discussion_train_3100.txt --testfile Discussion_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Advice --trainfile Advice_train_3100.txt --testfile Advice_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset CleanUp --trainfile CleanUp_train_3100.txt --testfile CleanUp_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Official --trainfile Official_train_3100.txt --testfile Official_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Factoid --trainfile Factoid_train_3100.txt --testfile Factoid_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Irrelevant --trainfile Irrelevant_train_3100.txt --testfile Irrelevant_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset PastNews --trainfile PastNews_train_3100.txt --testfile PastNews_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Hashtags --trainfile Hashtags_train_3100.txt --testfile Hashtags_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset SearchAndRescue --trainfile SearchAndRescue_train_3100.txt --testfile SearchAndRescue_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset ThirdPartyObservation --trainfile ThirdPartyObservation_train_3100.txt --testfile ThirdPartyObservation_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset MovePeople --trainfile MovePeople_train_3100.txt --testfile MovePeople_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Donations --trainfile Donations_train_3100.txt --testfile Donations_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset EmergingThreats --trainfile EmergingThreats_train_3100.txt --testfile EmergingThreats_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset ServiceAvailable --trainfile ServiceAvailable_train_3100.txt --testfile ServiceAvailable_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset ContinuingNews --trainfile ContinuingNews_train_3100.txt --testfile ContinuingNews_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Volunteer --trainfile Volunteer_train_3100.txt --testfile Volunteer_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Unknown --trainfile Unknown_train_3100.txt --testfile Unknown_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset Sentiment --trainfile Sentiment_train_3100.txt --testfile Sentiment_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset SignificantEventChange --trainfile SignificantEventChange_train_3100.txt --testfile SignificantEventChange_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset FirstPartyObservation --trainfile FirstPartyObservation_train_3100.txt --testfile FirstPartyObservation_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset MultimediaShare --trainfile MultimediaShare_train_3100.txt --testfile MultimediaShare_test_3100.txt --splits 10
python split_data.py --datafolder ../data/datasets/typhoonHagupit2014 --dataset KnownAlready --trainfile KnownAlready_train_3100.txt --testfile KnownAlready_test_3100.txt --splits 10
