%!/bin/bash

java -jar gadget_svm.jar data/datasets/albertaFloods2013/InformationWanted/config-pegasos.cfg data/datasets/albertaFloods2013/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Weather/config-pegasos.cfg data/datasets/albertaFloods2013/Weather/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/GoodsServices/config-pegasos.cfg data/datasets/albertaFloods2013/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Discussion/config-pegasos.cfg data/datasets/albertaFloods2013/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Advice/config-pegasos.cfg data/datasets/albertaFloods2013/Advice/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/CleanUp/config-pegasos.cfg data/datasets/albertaFloods2013/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Official/config-pegasos.cfg data/datasets/albertaFloods2013/Official/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Factoid/config-pegasos.cfg data/datasets/albertaFloods2013/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Irrelevant/config-pegasos.cfg data/datasets/albertaFloods2013/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/PastNews/config-pegasos.cfg data/datasets/albertaFloods2013/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Hashtags/config-pegasos.cfg data/datasets/albertaFloods2013/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/SearchAndRescue/config-pegasos.cfg data/datasets/albertaFloods2013/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/ThirdPartyObservation/config-pegasos.cfg data/datasets/albertaFloods2013/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/MovePeople/config-pegasos.cfg data/datasets/albertaFloods2013/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Donations/config-pegasos.cfg data/datasets/albertaFloods2013/Donations/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/EmergingThreats/config-pegasos.cfg data/datasets/albertaFloods2013/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/ServiceAvailable/config-pegasos.cfg data/datasets/albertaFloods2013/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/ContinuingNews/config-pegasos.cfg data/datasets/albertaFloods2013/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Volunteer/config-pegasos.cfg data/datasets/albertaFloods2013/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Unknown/config-pegasos.cfg data/datasets/albertaFloods2013/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/Sentiment/config-pegasos.cfg data/datasets/albertaFloods2013/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/SignificantEventChange/config-pegasos.cfg data/datasets/albertaFloods2013/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/FirstPartyObservation/config-pegasos.cfg data/datasets/albertaFloods2013/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/MultimediaShare/config-pegasos.cfg data/datasets/albertaFloods2013/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/albertaFloods2013/KnownAlready/config-pegasos.cfg data/datasets/albertaFloods2013/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/InformationWanted/config-pegasos.cfg data/datasets/queenslandFloods2013/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Weather/config-pegasos.cfg data/datasets/queenslandFloods2013/Weather/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/GoodsServices/config-pegasos.cfg data/datasets/queenslandFloods2013/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Discussion/config-pegasos.cfg data/datasets/queenslandFloods2013/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Advice/config-pegasos.cfg data/datasets/queenslandFloods2013/Advice/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/CleanUp/config-pegasos.cfg data/datasets/queenslandFloods2013/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Official/config-pegasos.cfg data/datasets/queenslandFloods2013/Official/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Factoid/config-pegasos.cfg data/datasets/queenslandFloods2013/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Irrelevant/config-pegasos.cfg data/datasets/queenslandFloods2013/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/PastNews/config-pegasos.cfg data/datasets/queenslandFloods2013/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Hashtags/config-pegasos.cfg data/datasets/queenslandFloods2013/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/SearchAndRescue/config-pegasos.cfg data/datasets/queenslandFloods2013/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/ThirdPartyObservation/config-pegasos.cfg data/datasets/queenslandFloods2013/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/MovePeople/config-pegasos.cfg data/datasets/queenslandFloods2013/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Donations/config-pegasos.cfg data/datasets/queenslandFloods2013/Donations/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/EmergingThreats/config-pegasos.cfg data/datasets/queenslandFloods2013/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/ServiceAvailable/config-pegasos.cfg data/datasets/queenslandFloods2013/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/ContinuingNews/config-pegasos.cfg data/datasets/queenslandFloods2013/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Volunteer/config-pegasos.cfg data/datasets/queenslandFloods2013/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Unknown/config-pegasos.cfg data/datasets/queenslandFloods2013/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/Sentiment/config-pegasos.cfg data/datasets/queenslandFloods2013/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/SignificantEventChange/config-pegasos.cfg data/datasets/queenslandFloods2013/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/FirstPartyObservation/config-pegasos.cfg data/datasets/queenslandFloods2013/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/MultimediaShare/config-pegasos.cfg data/datasets/queenslandFloods2013/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/queenslandFloods2013/KnownAlready/config-pegasos.cfg data/datasets/queenslandFloods2013/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/InformationWanted/config-pegasos.cfg data/datasets/Bombing_features/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/GoodsServices/config-pegasos.cfg data/datasets/Bombing_features/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Discussion/config-pegasos.cfg data/datasets/Bombing_features/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Advice/config-pegasos.cfg data/datasets/Bombing_features/Advice/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Official/config-pegasos.cfg data/datasets/Bombing_features/Official/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Factoid/config-pegasos.cfg data/datasets/Bombing_features/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Irrelevant/config-pegasos.cfg data/datasets/Bombing_features/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/PastNews/config-pegasos.cfg data/datasets/Bombing_features/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Hashtags/config-pegasos.cfg data/datasets/Bombing_features/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/ThirdPartyObservation/config-pegasos.cfg data/datasets/Bombing_features/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Donations/config-pegasos.cfg data/datasets/Bombing_features/Donations/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/EmergingThreats/config-pegasos.cfg data/datasets/Bombing_features/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/ServiceAvailable/config-pegasos.cfg data/datasets/Bombing_features/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/ContinuingNews/config-pegasos.cfg data/datasets/Bombing_features/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Volunteer/config-pegasos.cfg data/datasets/Bombing_features/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/Sentiment/config-pegasos.cfg data/datasets/Bombing_features/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/SignificantEventChange/config-pegasos.cfg data/datasets/Bombing_features/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/FirstPartyObservation/config-pegasos.cfg data/datasets/Bombing_features/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/MultimediaShare/config-pegasos.cfg data/datasets/Bombing_features/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/Bombing_features/KnownAlready/config-pegasos.cfg data/datasets/Bombing_features/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/InformationWanted/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Weather/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Weather/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/GoodsServices/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Discussion/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Advice/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Advice/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/CleanUp/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Official/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Official/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Factoid/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Irrelevant/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/PastNews/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Hashtags/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/SearchAndRescue/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/ThirdPartyObservation/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/MovePeople/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Donations/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Donations/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/EmergingThreats/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/ServiceAvailable/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/ContinuingNews/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Volunteer/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Unknown/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/Sentiment/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/SignificantEventChange/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/FirstPartyObservation/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/MultimediaShare/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/guatemalaEarthquake2012/KnownAlready/config-pegasos.cfg data/datasets/guatemalaEarthquake2012/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/InformationWanted/config-pegasos.cfg data/datasets/fire_features/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Weather/config-pegasos.cfg data/datasets/fire_features/Weather/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Discussion/config-pegasos.cfg data/datasets/fire_features/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Advice/config-pegasos.cfg data/datasets/fire_features/Advice/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Official/config-pegasos.cfg data/datasets/fire_features/Official/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Factoid/config-pegasos.cfg data/datasets/fire_features/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Irrelevant/config-pegasos.cfg data/datasets/fire_features/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/PastNews/config-pegasos.cfg data/datasets/fire_features/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/ThirdPartyObservation/config-pegasos.cfg data/datasets/fire_features/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/MovePeople/config-pegasos.cfg data/datasets/fire_features/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Donations/config-pegasos.cfg data/datasets/fire_features/Donations/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/EmergingThreats/config-pegasos.cfg data/datasets/fire_features/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/ServiceAvailable/config-pegasos.cfg data/datasets/fire_features/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/ContinuingNews/config-pegasos.cfg data/datasets/fire_features/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Volunteer/config-pegasos.cfg data/datasets/fire_features/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/Sentiment/config-pegasos.cfg data/datasets/fire_features/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/SignificantEventChange/config-pegasos.cfg data/datasets/fire_features/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/FirstPartyObservation/config-pegasos.cfg data/datasets/fire_features/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/MultimediaShare/config-pegasos.cfg data/datasets/fire_features/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/fire_features/KnownAlready/config-pegasos.cfg data/datasets/fire_features/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Discussion/config-pegasos.cfg data/datasets/Attacks_features/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Advice/config-pegasos.cfg data/datasets/Attacks_features/Advice/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Official/config-pegasos.cfg data/datasets/Attacks_features/Official/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Factoid/config-pegasos.cfg data/datasets/Attacks_features/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Irrelevant/config-pegasos.cfg data/datasets/Attacks_features/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Hashtags/config-pegasos.cfg data/datasets/Attacks_features/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/SearchAndRescue/config-pegasos.cfg data/datasets/Attacks_features/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/ThirdPartyObservation/config-pegasos.cfg data/datasets/Attacks_features/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/EmergingThreats/config-pegasos.cfg data/datasets/Attacks_features/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/ServiceAvailable/config-pegasos.cfg data/datasets/Attacks_features/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/ContinuingNews/config-pegasos.cfg data/datasets/Attacks_features/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Unknown/config-pegasos.cfg data/datasets/Attacks_features/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/Sentiment/config-pegasos.cfg data/datasets/Attacks_features/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/SignificantEventChange/config-pegasos.cfg data/datasets/Attacks_features/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/FirstPartyObservation/config-pegasos.cfg data/datasets/Attacks_features/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/MultimediaShare/config-pegasos.cfg data/datasets/Attacks_features/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/Attacks_features/KnownAlready/config-pegasos.cfg data/datasets/Attacks_features/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/InformationWanted/config-pegasos.cfg data/datasets/nepalEarthquake2015/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Weather/config-pegasos.cfg data/datasets/nepalEarthquake2015/Weather/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/GoodsServices/config-pegasos.cfg data/datasets/nepalEarthquake2015/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Discussion/config-pegasos.cfg data/datasets/nepalEarthquake2015/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Advice/config-pegasos.cfg data/datasets/nepalEarthquake2015/Advice/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/CleanUp/config-pegasos.cfg data/datasets/nepalEarthquake2015/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Official/config-pegasos.cfg data/datasets/nepalEarthquake2015/Official/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Factoid/config-pegasos.cfg data/datasets/nepalEarthquake2015/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Irrelevant/config-pegasos.cfg data/datasets/nepalEarthquake2015/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/PastNews/config-pegasos.cfg data/datasets/nepalEarthquake2015/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Hashtags/config-pegasos.cfg data/datasets/nepalEarthquake2015/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/SearchAndRescue/config-pegasos.cfg data/datasets/nepalEarthquake2015/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/ThirdPartyObservation/config-pegasos.cfg data/datasets/nepalEarthquake2015/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/MovePeople/config-pegasos.cfg data/datasets/nepalEarthquake2015/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Donations/config-pegasos.cfg data/datasets/nepalEarthquake2015/Donations/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/EmergingThreats/config-pegasos.cfg data/datasets/nepalEarthquake2015/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/ServiceAvailable/config-pegasos.cfg data/datasets/nepalEarthquake2015/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/ContinuingNews/config-pegasos.cfg data/datasets/nepalEarthquake2015/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Volunteer/config-pegasos.cfg data/datasets/nepalEarthquake2015/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Unknown/config-pegasos.cfg data/datasets/nepalEarthquake2015/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/Sentiment/config-pegasos.cfg data/datasets/nepalEarthquake2015/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/SignificantEventChange/config-pegasos.cfg data/datasets/nepalEarthquake2015/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/FirstPartyObservation/config-pegasos.cfg data/datasets/nepalEarthquake2015/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/MultimediaShare/config-pegasos.cfg data/datasets/nepalEarthquake2015/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/nepalEarthquake2015/KnownAlready/config-pegasos.cfg data/datasets/nepalEarthquake2015/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/InformationWanted/config-pegasos.cfg data/datasets/manilaFloods2013/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Weather/config-pegasos.cfg data/datasets/manilaFloods2013/Weather/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/GoodsServices/config-pegasos.cfg data/datasets/manilaFloods2013/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Discussion/config-pegasos.cfg data/datasets/manilaFloods2013/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Advice/config-pegasos.cfg data/datasets/manilaFloods2013/Advice/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/CleanUp/config-pegasos.cfg data/datasets/manilaFloods2013/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Official/config-pegasos.cfg data/datasets/manilaFloods2013/Official/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Factoid/config-pegasos.cfg data/datasets/manilaFloods2013/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Irrelevant/config-pegasos.cfg data/datasets/manilaFloods2013/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/PastNews/config-pegasos.cfg data/datasets/manilaFloods2013/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Hashtags/config-pegasos.cfg data/datasets/manilaFloods2013/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/SearchAndRescue/config-pegasos.cfg data/datasets/manilaFloods2013/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/ThirdPartyObservation/config-pegasos.cfg data/datasets/manilaFloods2013/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/MovePeople/config-pegasos.cfg data/datasets/manilaFloods2013/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Donations/config-pegasos.cfg data/datasets/manilaFloods2013/Donations/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/EmergingThreats/config-pegasos.cfg data/datasets/manilaFloods2013/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/ServiceAvailable/config-pegasos.cfg data/datasets/manilaFloods2013/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/ContinuingNews/config-pegasos.cfg data/datasets/manilaFloods2013/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Volunteer/config-pegasos.cfg data/datasets/manilaFloods2013/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Unknown/config-pegasos.cfg data/datasets/manilaFloods2013/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/Sentiment/config-pegasos.cfg data/datasets/manilaFloods2013/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/SignificantEventChange/config-pegasos.cfg data/datasets/manilaFloods2013/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/FirstPartyObservation/config-pegasos.cfg data/datasets/manilaFloods2013/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/MultimediaShare/config-pegasos.cfg data/datasets/manilaFloods2013/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/manilaFloods2013/KnownAlready/config-pegasos.cfg data/datasets/manilaFloods2013/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/InformationWanted/config-pegasos.cfg data/datasets/Tornado_features/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Weather/config-pegasos.cfg data/datasets/Tornado_features/Weather/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/GoodsServices/config-pegasos.cfg data/datasets/Tornado_features/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Discussion/config-pegasos.cfg data/datasets/Tornado_features/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Advice/config-pegasos.cfg data/datasets/Tornado_features/Advice/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/CleanUp/config-pegasos.cfg data/datasets/Tornado_features/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Official/config-pegasos.cfg data/datasets/Tornado_features/Official/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Factoid/config-pegasos.cfg data/datasets/Tornado_features/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Irrelevant/config-pegasos.cfg data/datasets/Tornado_features/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Hashtags/config-pegasos.cfg data/datasets/Tornado_features/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/SearchAndRescue/config-pegasos.cfg data/datasets/Tornado_features/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/ThirdPartyObservation/config-pegasos.cfg data/datasets/Tornado_features/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/MovePeople/config-pegasos.cfg data/datasets/Tornado_features/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Donations/config-pegasos.cfg data/datasets/Tornado_features/Donations/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/EmergingThreats/config-pegasos.cfg data/datasets/Tornado_features/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/ServiceAvailable/config-pegasos.cfg data/datasets/Tornado_features/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/ContinuingNews/config-pegasos.cfg data/datasets/Tornado_features/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Volunteer/config-pegasos.cfg data/datasets/Tornado_features/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Unknown/config-pegasos.cfg data/datasets/Tornado_features/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/Sentiment/config-pegasos.cfg data/datasets/Tornado_features/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/SignificantEventChange/config-pegasos.cfg data/datasets/Tornado_features/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/FirstPartyObservation/config-pegasos.cfg data/datasets/Tornado_features/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Tornado_features/MultimediaShare/config-pegasos.cfg data/datasets/Tornado_features/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/InformationWanted/config-pegasos.cfg data/datasets/Shooting_features/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Discussion/config-pegasos.cfg data/datasets/Shooting_features/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Advice/config-pegasos.cfg data/datasets/Shooting_features/Advice/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/CleanUp/config-pegasos.cfg data/datasets/Shooting_features/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Factoid/config-pegasos.cfg data/datasets/Shooting_features/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Irrelevant/config-pegasos.cfg data/datasets/Shooting_features/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/PastNews/config-pegasos.cfg data/datasets/Shooting_features/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Hashtags/config-pegasos.cfg data/datasets/Shooting_features/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/ThirdPartyObservation/config-pegasos.cfg data/datasets/Shooting_features/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Donations/config-pegasos.cfg data/datasets/Shooting_features/Donations/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/EmergingThreats/config-pegasos.cfg data/datasets/Shooting_features/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/ContinuingNews/config-pegasos.cfg data/datasets/Shooting_features/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Volunteer/config-pegasos.cfg data/datasets/Shooting_features/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/Sentiment/config-pegasos.cfg data/datasets/Shooting_features/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/FirstPartyObservation/config-pegasos.cfg data/datasets/Shooting_features/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/MultimediaShare/config-pegasos.cfg data/datasets/Shooting_features/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/Shooting_features/KnownAlready/config-pegasos.cfg data/datasets/Shooting_features/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/InformationWanted/config-pegasos.cfg data/datasets/chileEarthquake2014/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Weather/config-pegasos.cfg data/datasets/chileEarthquake2014/Weather/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/GoodsServices/config-pegasos.cfg data/datasets/chileEarthquake2014/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Discussion/config-pegasos.cfg data/datasets/chileEarthquake2014/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Advice/config-pegasos.cfg data/datasets/chileEarthquake2014/Advice/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/CleanUp/config-pegasos.cfg data/datasets/chileEarthquake2014/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Official/config-pegasos.cfg data/datasets/chileEarthquake2014/Official/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Factoid/config-pegasos.cfg data/datasets/chileEarthquake2014/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Irrelevant/config-pegasos.cfg data/datasets/chileEarthquake2014/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/PastNews/config-pegasos.cfg data/datasets/chileEarthquake2014/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Hashtags/config-pegasos.cfg data/datasets/chileEarthquake2014/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/SearchAndRescue/config-pegasos.cfg data/datasets/chileEarthquake2014/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/ThirdPartyObservation/config-pegasos.cfg data/datasets/chileEarthquake2014/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/MovePeople/config-pegasos.cfg data/datasets/chileEarthquake2014/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Donations/config-pegasos.cfg data/datasets/chileEarthquake2014/Donations/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/EmergingThreats/config-pegasos.cfg data/datasets/chileEarthquake2014/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/ServiceAvailable/config-pegasos.cfg data/datasets/chileEarthquake2014/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/ContinuingNews/config-pegasos.cfg data/datasets/chileEarthquake2014/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Volunteer/config-pegasos.cfg data/datasets/chileEarthquake2014/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Unknown/config-pegasos.cfg data/datasets/chileEarthquake2014/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/Sentiment/config-pegasos.cfg data/datasets/chileEarthquake2014/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/SignificantEventChange/config-pegasos.cfg data/datasets/chileEarthquake2014/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/FirstPartyObservation/config-pegasos.cfg data/datasets/chileEarthquake2014/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/MultimediaShare/config-pegasos.cfg data/datasets/chileEarthquake2014/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/chileEarthquake2014/KnownAlready/config-pegasos.cfg data/datasets/chileEarthquake2014/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/InformationWanted/config-pegasos.cfg data/datasets/philipinnesFloods2012/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Weather/config-pegasos.cfg data/datasets/philipinnesFloods2012/Weather/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/GoodsServices/config-pegasos.cfg data/datasets/philipinnesFloods2012/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Discussion/config-pegasos.cfg data/datasets/philipinnesFloods2012/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Advice/config-pegasos.cfg data/datasets/philipinnesFloods2012/Advice/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/CleanUp/config-pegasos.cfg data/datasets/philipinnesFloods2012/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Official/config-pegasos.cfg data/datasets/philipinnesFloods2012/Official/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Factoid/config-pegasos.cfg data/datasets/philipinnesFloods2012/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Irrelevant/config-pegasos.cfg data/datasets/philipinnesFloods2012/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/PastNews/config-pegasos.cfg data/datasets/philipinnesFloods2012/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Hashtags/config-pegasos.cfg data/datasets/philipinnesFloods2012/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/SearchAndRescue/config-pegasos.cfg data/datasets/philipinnesFloods2012/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/ThirdPartyObservation/config-pegasos.cfg data/datasets/philipinnesFloods2012/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/MovePeople/config-pegasos.cfg data/datasets/philipinnesFloods2012/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Donations/config-pegasos.cfg data/datasets/philipinnesFloods2012/Donations/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/EmergingThreats/config-pegasos.cfg data/datasets/philipinnesFloods2012/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/ServiceAvailable/config-pegasos.cfg data/datasets/philipinnesFloods2012/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/ContinuingNews/config-pegasos.cfg data/datasets/philipinnesFloods2012/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Volunteer/config-pegasos.cfg data/datasets/philipinnesFloods2012/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Unknown/config-pegasos.cfg data/datasets/philipinnesFloods2012/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/Sentiment/config-pegasos.cfg data/datasets/philipinnesFloods2012/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/SignificantEventChange/config-pegasos.cfg data/datasets/philipinnesFloods2012/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/FirstPartyObservation/config-pegasos.cfg data/datasets/philipinnesFloods2012/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/MultimediaShare/config-pegasos.cfg data/datasets/philipinnesFloods2012/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/philipinnesFloods2012/KnownAlready/config-pegasos.cfg data/datasets/philipinnesFloods2012/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/InformationWanted/config-pegasos.cfg data/datasets/typhoonYolanda2013/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Weather/config-pegasos.cfg data/datasets/typhoonYolanda2013/Weather/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/GoodsServices/config-pegasos.cfg data/datasets/typhoonYolanda2013/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Discussion/config-pegasos.cfg data/datasets/typhoonYolanda2013/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Advice/config-pegasos.cfg data/datasets/typhoonYolanda2013/Advice/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/CleanUp/config-pegasos.cfg data/datasets/typhoonYolanda2013/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Official/config-pegasos.cfg data/datasets/typhoonYolanda2013/Official/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Factoid/config-pegasos.cfg data/datasets/typhoonYolanda2013/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Irrelevant/config-pegasos.cfg data/datasets/typhoonYolanda2013/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/PastNews/config-pegasos.cfg data/datasets/typhoonYolanda2013/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Hashtags/config-pegasos.cfg data/datasets/typhoonYolanda2013/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/SearchAndRescue/config-pegasos.cfg data/datasets/typhoonYolanda2013/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/ThirdPartyObservation/config-pegasos.cfg data/datasets/typhoonYolanda2013/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/MovePeople/config-pegasos.cfg data/datasets/typhoonYolanda2013/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Donations/config-pegasos.cfg data/datasets/typhoonYolanda2013/Donations/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/EmergingThreats/config-pegasos.cfg data/datasets/typhoonYolanda2013/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/ServiceAvailable/config-pegasos.cfg data/datasets/typhoonYolanda2013/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/ContinuingNews/config-pegasos.cfg data/datasets/typhoonYolanda2013/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Volunteer/config-pegasos.cfg data/datasets/typhoonYolanda2013/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Unknown/config-pegasos.cfg data/datasets/typhoonYolanda2013/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/Sentiment/config-pegasos.cfg data/datasets/typhoonYolanda2013/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/SignificantEventChange/config-pegasos.cfg data/datasets/typhoonYolanda2013/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/FirstPartyObservation/config-pegasos.cfg data/datasets/typhoonYolanda2013/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/MultimediaShare/config-pegasos.cfg data/datasets/typhoonYolanda2013/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/typhoonYolanda2013/KnownAlready/config-pegasos.cfg data/datasets/typhoonYolanda2013/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/InformationWanted/config-pegasos.cfg data/datasets/italyEarthquakes2012/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Weather/config-pegasos.cfg data/datasets/italyEarthquakes2012/Weather/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/GoodsServices/config-pegasos.cfg data/datasets/italyEarthquakes2012/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Discussion/config-pegasos.cfg data/datasets/italyEarthquakes2012/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Advice/config-pegasos.cfg data/datasets/italyEarthquakes2012/Advice/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/CleanUp/config-pegasos.cfg data/datasets/italyEarthquakes2012/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Official/config-pegasos.cfg data/datasets/italyEarthquakes2012/Official/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Factoid/config-pegasos.cfg data/datasets/italyEarthquakes2012/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Irrelevant/config-pegasos.cfg data/datasets/italyEarthquakes2012/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/PastNews/config-pegasos.cfg data/datasets/italyEarthquakes2012/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Hashtags/config-pegasos.cfg data/datasets/italyEarthquakes2012/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/SearchAndRescue/config-pegasos.cfg data/datasets/italyEarthquakes2012/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/ThirdPartyObservation/config-pegasos.cfg data/datasets/italyEarthquakes2012/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/MovePeople/config-pegasos.cfg data/datasets/italyEarthquakes2012/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Donations/config-pegasos.cfg data/datasets/italyEarthquakes2012/Donations/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/EmergingThreats/config-pegasos.cfg data/datasets/italyEarthquakes2012/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/ServiceAvailable/config-pegasos.cfg data/datasets/italyEarthquakes2012/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/ContinuingNews/config-pegasos.cfg data/datasets/italyEarthquakes2012/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Volunteer/config-pegasos.cfg data/datasets/italyEarthquakes2012/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Unknown/config-pegasos.cfg data/datasets/italyEarthquakes2012/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/Sentiment/config-pegasos.cfg data/datasets/italyEarthquakes2012/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/SignificantEventChange/config-pegasos.cfg data/datasets/italyEarthquakes2012/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/FirstPartyObservation/config-pegasos.cfg data/datasets/italyEarthquakes2012/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/MultimediaShare/config-pegasos.cfg data/datasets/italyEarthquakes2012/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/italyEarthquakes2012/KnownAlready/config-pegasos.cfg data/datasets/italyEarthquakes2012/KnownAlready/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/InformationWanted/config-pegasos.cfg data/datasets/typhoonHagupit2014/InformationWanted/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Weather/config-pegasos.cfg data/datasets/typhoonHagupit2014/Weather/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/GoodsServices/config-pegasos.cfg data/datasets/typhoonHagupit2014/GoodsServices/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Discussion/config-pegasos.cfg data/datasets/typhoonHagupit2014/Discussion/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Advice/config-pegasos.cfg data/datasets/typhoonHagupit2014/Advice/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/CleanUp/config-pegasos.cfg data/datasets/typhoonHagupit2014/CleanUp/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Official/config-pegasos.cfg data/datasets/typhoonHagupit2014/Official/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Factoid/config-pegasos.cfg data/datasets/typhoonHagupit2014/Factoid/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Irrelevant/config-pegasos.cfg data/datasets/typhoonHagupit2014/Irrelevant/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/PastNews/config-pegasos.cfg data/datasets/typhoonHagupit2014/PastNews/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Hashtags/config-pegasos.cfg data/datasets/typhoonHagupit2014/Hashtags/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/SearchAndRescue/config-pegasos.cfg data/datasets/typhoonHagupit2014/SearchAndRescue/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/ThirdPartyObservation/config-pegasos.cfg data/datasets/typhoonHagupit2014/ThirdPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/MovePeople/config-pegasos.cfg data/datasets/typhoonHagupit2014/MovePeople/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Donations/config-pegasos.cfg data/datasets/typhoonHagupit2014/Donations/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/EmergingThreats/config-pegasos.cfg data/datasets/typhoonHagupit2014/EmergingThreats/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/ServiceAvailable/config-pegasos.cfg data/datasets/typhoonHagupit2014/ServiceAvailable/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/ContinuingNews/config-pegasos.cfg data/datasets/typhoonHagupit2014/ContinuingNews/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Volunteer/config-pegasos.cfg data/datasets/typhoonHagupit2014/Volunteer/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Unknown/config-pegasos.cfg data/datasets/typhoonHagupit2014/Unknown/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/Sentiment/config-pegasos.cfg data/datasets/typhoonHagupit2014/Sentiment/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/SignificantEventChange/config-pegasos.cfg data/datasets/typhoonHagupit2014/SignificantEventChange/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/FirstPartyObservation/config-pegasos.cfg data/datasets/typhoonHagupit2014/FirstPartyObservation/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/MultimediaShare/config-pegasos.cfg data/datasets/typhoonHagupit2014/MultimediaShare/output.txt
java -jar gadget_svm.jar data/datasets/typhoonHagupit2014/KnownAlready/config-pegasos.cfg data/datasets/typhoonHagupit2014/KnownAlready/output.txt
